const level1 = new Level(
    [

        new Chicken(),
        new Chicken(),
        new smallChicken(),
        new Chicken(),
        new Chicken(),
        new smallChicken(),
        new Chicken(),
        new Chicken(),
        new smallChicken(),
        new smallChicken(),
        new Boss(),
    ],
    [
        new CloudA(),
        new CloudB(),
        new CloudA(),
        new CloudB(),
        new CloudA(),
        new CloudA(),
        new CloudB(),
        new CloudB(),
        new CloudA(),
        new CloudB(),
        new CloudA(),
        new CloudB(),
        new CloudA(),
        new CloudA(),
        new CloudB(),
        new CloudB(),
        new CloudA(),
        new CloudB(),
        new CloudA(),
        new CloudB(),
        new CloudA(),
        new CloudA(),
        new CloudB(),
        new CloudB(),
    ],
    [
        new BackgoundObject('img/5_background/layers/air.png', -1 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', -1 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', -1 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', -1 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 0 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 0 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 0 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 0 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 1 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 1 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 1 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 1 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 2 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 2 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 2 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 2 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 3 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 3 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 3 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 3 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 4 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 4 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 4 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 4 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 5 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 5 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 5 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 5 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 6 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 6 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 6 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 6 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 7 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 7 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 7 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 7 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 8 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 9 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 10 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 10 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 10 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 10 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 11 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 11 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 11 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 11 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 12 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/1.png', 12 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/1.png', 12 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/1.png', 12 * 719),
        new BackgoundObject('img/5_background/layers/air.png', 13 * 719),
        new BackgoundObject('img/5_background/layers/3_third_layer/2.png', 13 * 719),
        new BackgoundObject('img/5_background/layers/2_second_layer/2.png', 13 * 719),
        new BackgoundObject('img/5_background/layers/1_first_layer/2.png', 13 * 719),

    ],
    [
              new Coin(719 * 3.2),
              new Coin(219 * 4.4),
              new Coin(419 * 6.3),
              new Coin(319 * 7.8),
              new Coin(219 * 9.5),
    ],

    [
              new Ammo(719 * 3.2),
              new Ammo(319 * 4.4),
              new Ammo(519 * 6.3),
              new Ammo(619 * 7.8),
              new Ammo(119 * 9.5),
    ],
)